services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1
    command: flask run -h 0.0.0.0
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nopalli
